### ISSUE TITLE
Runtime error when executing solver payout script

### ISSUE THREAD

**Issue by bh2smith** [cowprotocol/solver-rewards#9]
**nlordell:** I ran into this intermittent error when executing the solver payout script:
```
% python -m src.fetch.transfer_file --start '2022-03-22'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/nlordell/Developer/solver-rewards/src/fetch/transfer_file.py", line 134, in <module>
    transfers = get_transfers(
  File "/Users/nlordell/Developer/solver-rewards/src/fetch/transfer_file.py", line 112, in get_transfers
    transfer = Transfer.from_dict(row)
  File "/Users/nlordell/Developer/solver-rewards/src/fetch/transfer_file.py", line 64, in from_dict
    token_type = TokenType.from_str(obj["token_type"])
KeyError: 'token_type'
```

**bh2smith:** This happens sometimes in situations when the return data doesn't match what is expected from the query. I think we would need to improve logging at the call site to get a better idea of what this non-conforming but also non-empty return data looks like. Then we can handle the exception at an earlier stage. Unfortunately this issue is not forcibly reproducible. Will add to the todo list!

Thanks for reporting!

**Comment by bh2smith** [comment]
This issue arises when two people are logged into the same account at the same time and calling fetch with the same query ID. There is a race condition that one user might see the output of a different query and then it won't be parsable (i.e. the key error)
