### ISSUE TITLE
The `fetch.period_totals` Script Is Not Working

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/solver-rewards#93]
There are two issues:

1. It looks like the path in the script is wrong:
```
% python -m src.fetch.period_totals --start '2022-02-01'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/nlordell/Developer/cowprotocol/solver-rewards/src/fetch/period_totals.py", line 52, in <module>
    total_for_period = get_period_totals(dune=args.dune, period=args.period)
  File "/Users/nlordell/Developer/cowprotocol/solver-rewards/src/fetch/period_totals.py", line 30, in get_period_totals
    raw_sql=open_query("./dashboards/period-totals.sql"),
  File "/Users/nlordell/Developer/cowprotocol/solver-rewards/venv/lib/python3.10/site-packages/duneapi/util.py", line 29, in open_query
    with open(filepath, "r", encoding="utf-8") as query_file:
FileNotFoundError: [Errno 2] No such file or directory: './dashboards/period-totals.sql'
```

2. Fixing the path isn't enough, 
```
% python -m src.fetch.period_totals --start '2022-10-04'
2022-10-10 16:11:50,918 INFO duneapi.api Fetching Accounting Period Totals on Ethereum Mainnet...
2022-10-10 16:11:57,484 WARNING duneapi.api failed with Dune API Request failed with errors [{'id': 'a1fc4805-cc8b-4cb2-bd5b-7be5977295bd', 'job_id': '339d4989-bfff-4bcd-96da-88080414912e', 'runtime': None, 'message': 'the following keys in the query do not have matching parameters: PerBatchReward, PerTradeReward', 'metadata': {'keys': ['PerBatchReward', 'PerTradeReward']}, 'type': 'missing_parameters', 'generated_at': '2022-10-10T14:11:54.759404+00:00'}]. Re-establishing connection and trying again
```

**Comment by bh2smith** [comment]
Thanks for reporting, I will get it fixed soon. Is there any particular reason you were looking at this script? I don't believe we even use this anymore in the payout script.

**Comment by nlordell** [comment]
I just wanted to:
> To fetch the total eth spent, realized fees and cow rewards for an accounting period run the period totals script as follows

And followed the README.

> I don't believe we even use this anymore in the payout script.

If the script is deprecated and not maintained anymore, I would suggest removing the script entirely and removing it from the README. I don't think we need to waste development time on keeping old scripts working (and they are in version control if they ever need to be revived). To me (coming back to this repo after a while, and forgot what script should run, but also to others trying to run this for the first time), it was confusing that the first example of how to use the repo was pointing to this script, and it didn't work.

**Comment by bh2smith** [comment]
Well it is still part off the dashboard so I guess it's probably best that we do maintain it. I'll fix ASAP.
